sonar.organization=disciplinapro
sonar.projectKey=disciplinapro_Disciplina-PRO
sonar.projectName=Disciplina PRO
sonar.sourceEncoding=UTF-8

sonar.sources=frontend/src,backend/src
sonar.tests=frontend/src,backend/src,backend/test
sonar.test.inclusions=**/*.test.js,**/*.component.test.jsx,frontend/src/test/**,**/*.spec.ts,**/*.e2e-spec.ts,**/*.integration-spec.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,frontend/*.html
sonar.coverage.exclusions=backend/src/main.ts,backend/src/generated/**,frontend/src/test/**,**/*.config.js,**/*.config.mjs
sonar.cpd.exclusions=**/*.test.js,**/*.component.test.jsx,frontend/src/test/**,**/*.spec.ts,**/*.e2e-spec.ts,**/*.integration-spec.ts

sonar.javascript.lcov.reportPaths=frontend/coverage/unit/lcov.info,frontend/coverage/components/lcov.info,backend/coverage/unit/lcov.info,backend/coverage/integration/lcov.info,backend/coverage/e2e/lcov.info
