sonar.organization=edusobreiraa
sonar.projectKey=EduSobreiraa_Disciplina-PRO
sonar.projectName=Disciplina PRO
sonar.sourceEncoding=UTF-8

sonar.sources=frontend/src,backend/src
sonar.tests=frontend/src,backend/src,backend/test
sonar.test.inclusions=**/*.test.js,**/*.spec.ts,**/*.e2e-spec.ts,**/*.integration-spec.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,frontend/*.html
sonar.coverage.exclusions=backend/src/main.ts,**/*.config.js,**/*.config.mjs
sonar.cpd.exclusions=**/*.test.js,**/*.spec.ts,**/*.e2e-spec.ts,**/*.integration-spec.ts

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
