import type { TenantRole } from '../application/organization-context.repository.js'

export const TENANT_PERMISSIONS = {
  MEMBERSHIP_READ_SELF: 'MEMBERSHIP_READ_SELF',
  MEMBERSHIP_READ_SCOPED: 'MEMBERSHIP_READ_SCOPED',
  MEMBERSHIP_INACTIVATE_SCOPED: 'MEMBERSHIP_INACTIVATE_SCOPED',
  MEMBERSHIP_REACTIVATE_SCOPED: 'MEMBERSHIP_REACTIVATE_SCOPED',
  MEMBERSHIP_SUSPEND: 'MEMBERSHIP_SUSPEND',
  MEMBERSHIP_CHANGE_ROLE: 'MEMBERSHIP_CHANGE_ROLE',
  TEAM_READ_ASSIGNED: 'TEAM_READ_ASSIGNED',
  TEAM_READ_ALL: 'TEAM_READ_ALL',
  TEAM_CREATE: 'TEAM_CREATE',
  TEAM_UPDATE: 'TEAM_UPDATE',
  TEAM_ARCHIVE: 'TEAM_ARCHIVE',
  TEAM_RESTORE: 'TEAM_RESTORE',
  TEAM_MEMBERS_READ_SCOPED: 'TEAM_MEMBERS_READ_SCOPED',
  TEAM_MEMBERS_ASSIGN: 'TEAM_MEMBERS_ASSIGN',
  TEAM_MANAGERS_ASSIGN: 'TEAM_MANAGERS_ASSIGN',
  INVITATION_READ_SCOPED: 'INVITATION_READ_SCOPED',
  INVITATION_CREATE_SCOPED: 'INVITATION_CREATE_SCOPED',
  INVITATION_RESEND_SCOPED: 'INVITATION_RESEND_SCOPED',
  INVITATION_REVOKE_SCOPED: 'INVITATION_REVOKE_SCOPED',
  AUDIT_READ_SELF: 'AUDIT_READ_SELF',
  AUDIT_READ_TEAM: 'AUDIT_READ_TEAM',
  AUDIT_READ_TENANT: 'AUDIT_READ_TENANT',
  REPORT_READ_SELF: 'REPORT_READ_SELF',
  REPORT_READ_TEAM: 'REPORT_READ_TEAM',
  REPORT_READ_TENANT: 'REPORT_READ_TENANT',
} as const

export type TenantPermission = (typeof TENANT_PERMISSIONS)[keyof typeof TENANT_PERMISSIONS]

const USER_PERMISSIONS = new Set<TenantPermission>([
  TENANT_PERMISSIONS.MEMBERSHIP_READ_SELF,
  TENANT_PERMISSIONS.TEAM_READ_ASSIGNED,
  TENANT_PERMISSIONS.AUDIT_READ_SELF,
  TENANT_PERMISSIONS.REPORT_READ_SELF,
])

const MANAGER_PERMISSIONS = new Set<TenantPermission>([
  ...USER_PERMISSIONS,
  TENANT_PERMISSIONS.MEMBERSHIP_READ_SCOPED,
  TENANT_PERMISSIONS.MEMBERSHIP_INACTIVATE_SCOPED,
  TENANT_PERMISSIONS.MEMBERSHIP_REACTIVATE_SCOPED,
  TENANT_PERMISSIONS.TEAM_MEMBERS_READ_SCOPED,
  TENANT_PERMISSIONS.INVITATION_READ_SCOPED,
  TENANT_PERMISSIONS.INVITATION_CREATE_SCOPED,
  TENANT_PERMISSIONS.INVITATION_RESEND_SCOPED,
  TENANT_PERMISSIONS.INVITATION_REVOKE_SCOPED,
  TENANT_PERMISSIONS.AUDIT_READ_TEAM,
  TENANT_PERMISSIONS.REPORT_READ_TEAM,
])

const CEO_PERMISSIONS = new Set<TenantPermission>([
  ...MANAGER_PERMISSIONS,
  TENANT_PERMISSIONS.MEMBERSHIP_SUSPEND,
  TENANT_PERMISSIONS.MEMBERSHIP_CHANGE_ROLE,
  TENANT_PERMISSIONS.TEAM_READ_ALL,
  TENANT_PERMISSIONS.TEAM_CREATE,
  TENANT_PERMISSIONS.TEAM_UPDATE,
  TENANT_PERMISSIONS.TEAM_ARCHIVE,
  TENANT_PERMISSIONS.TEAM_RESTORE,
  TENANT_PERMISSIONS.TEAM_MEMBERS_ASSIGN,
  TENANT_PERMISSIONS.TEAM_MANAGERS_ASSIGN,
  TENANT_PERMISSIONS.AUDIT_READ_TENANT,
  TENANT_PERMISSIONS.REPORT_READ_TENANT,
])

const PERMISSIONS_BY_ROLE: Readonly<Record<TenantRole, ReadonlySet<TenantPermission>>> = {
  USER: USER_PERMISSIONS,
  MANAGER: MANAGER_PERMISSIONS,
  CEO: CEO_PERMISSIONS,
}

export function roleHasTenantPermissions(role: TenantRole, required: readonly TenantPermission[]) {
  const granted = PERMISSIONS_BY_ROLE[role]
  return required.every((permission) => granted.has(permission))
}
